jobs:
  include:
    #- stage: test
    #  matrix:
    #    include:
    - stage: lint
      matrix:
        include:
          - language: go
            install:
              - go get -u golang.org/x/lint/golint
            script:
              - golint ./...
    #- stage: deploy
    #  matrix:
    #    include:
