
matrix:
  include:
    - language: go
      go_import_path: github.com/petelliott/shooty-game
      before_script:
        - go get -u golang.org/x/lint/golint
      script:
        - golint ./...
        - go test -cover ./...

